// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yanplarzyqewurnmhsnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhbnBsYXJ6eXFld3Vybm1oc253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDI5NzksImV4cCI6MjA2MDYxODk3OX0.QV0VGRpfdTlL1GDRy7kzrnnKdDI1RsQKHVyPPLeI1Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);