
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tauhvfyhkqvwkgqeucib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdWh2Znloa3F2d2tncWV1Y2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA0MjgwNDgsImV4cCI6MjAyNjAwNDA0OH0.iOBWFfiSiP2LRYXF1AGMNq3p-JKdNk3ytgw309Hhg8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
